project:
  type: website
  output-dir: docs
website:
  title: "Connor Anderson"

  navbar:
    right:
      - text: Home
        href: index.qmd
      - text: Projects
        href: Projects.qmd
      - text: Resume
        href: Resume.qmd

format:
  html:
    theme: cosmo
    css: styles.css

editor: visual
